### ISSUE TITLE
Error: Cannot find module '@vue/babel-preset-app'

### ISSUE THREAD

**Issue by itsMagondu** [davellanedam/vue-skeleton-mvp#235]
**Describe the bug**
Thanks for an amazing boilerplate. I keep experiencing a failed start though. Whenever I try to start using `yarn serve`, I get the error

**To Reproduce**
I decided to use yarn instead of npm.
- Clone the repo
- Run `yarn` to install packages.
- Run `yarn serve` to start the project

**Expected behavior**
vue-cli should successfully serve the app locally. The simple fix has been to install @vue/babel-preset-app using the command
`yarn add -D @vue/babel-preset-app`

Is anyone else experiencing the same issue? I can create a PR to resolve it but I find it strange that no one might have experienced this.

**Screenshots**
![image](https://user-images.githubusercontent.com/1202275/79139958-e4425780-7dbf-11ea-9f87-e6b84031270d.png)

**Comment by markim** [comment]
Can confirm that the project does not work out of the box using yarn.

However, after adding the developer dependency (I used npm, because this project so far has always used npm over yarn) with:

`npm install @vue/babel-preset-app --save-dev`

This will allow yarn to install, then serve the app with `yarn serve`.

Personal thoughts after learning a little bit more of the history of npm/yarn https://javascript.christmas/2019/10 and developing with a few projects using npm and yarn:

- yarn is a little faster on install
- I like running `yarn upgrade-interactive` to pick and choose which package to update over cmd line
- project build pipeline I believe is using `npm ci`, but we could still commit a yarn.lock file without interruptions
- npm more mature (and recently bought by github aka microsoft :P)

@davellanedam what do you think? I don't think adding this package and a yarn.lock would affect anything. Most npm packages say "install with npm x, or install with yarn y"

**Comment by davellanedam** [comment]
Hey @itsMagondu I'm sorry, I use npm, I added `@vue/babel-preset-app` in `package.json`. Version https://github.com/davellanedam/vue-skeleton-mvp/releases/tag/v5.0.5 should fix the problem. I'm OK if you guys think adding `yarn.lock`, maybe a PR for that, pros/cons? Thanks @markim for doing some research on this.

**Comment by itsMagondu** [comment]
Thanks @davellanedam I think adding `@vue/babel-preset-app` to package.json should be enough. Yarn complains when you have both yarn.lock and package-json.lock. It is actually not a good idea.
